### ISSUE TITLE
Set nginx to 301 redirect all www.louisville.io URLs to louisville.io

### ISSUE THREAD

**Issue by ericlathrop** [louisvilleio/louisville.io-ansible#2]
People will manually enter www.louisville.io, so we must make sure the URL works, but redirects to the canonical URL of louisville.io.

**Comment by slogsdon** [comment]
is that vhost the default for the box? the [config](https://github.com/louisvilleio/louisville.io-ansible/blob/master/roles/web/files/louisville.io.conf) only sets the `server_name` to localhost

**Comment by ericlathrop** [comment]
No idea what that means. If someone doesn't include a host header it should serve the louisville.io site by default.

**Comment by ericlathrop** [comment]
This is now fixed! Thanks so much @SeanSith! :+1:
